# Generated by Django 4.2 on 2023-09-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('member_id', models.CharField(default=0, max_length=30)),
                ('admin_id', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
