# Generated by Django 4.2 on 2023-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin_id',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='member_id',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
