# Generated by Django 4.2 on 2023-09-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_admin_id_group_member_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group',
            new_name='groups',
        ),
    ]
