# Generated by Django 4.2 on 2023-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_group_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_post_and_delete', 'Can post and delete')],
            },
        ),
    ]
